import { config } from 'dotenv';
config();

const {
  PORT,
  TEST_PORT,
  JWT_SECRET_KEY,
  NODE_ENV,
  SERVER_IP,
  DB_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET,
  GMAIL_REFRESH_TOKEN,
  GMAIL_SENDER_EMAIL,
  MAX_QUERY_COMPLEXITY,
  QUERY_DEPTH_LIMIT,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_USER_ID_TIMEFRAME_SECONDS,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_USER_ID_VALUE,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_IP_TIMEFRAME_SECONDS,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_IP_VALUE
} = process.env as {
  [key: string]: string;
};

export const env = {
  PORT,
  TEST_PORT,
  JWT_SECRET_KEY,
  NODE_ENV,
  SERVER_IP,
  DB_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET,
  GMAIL_REFRESH_TOKEN,
  GMAIL_SENDER_EMAIL,
  MAX_QUERY_COMPLEXITY,
  QUERY_DEPTH_LIMIT,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_USER_ID_TIMEFRAME_SECONDS,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_USER_ID_VALUE,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_IP_TIMEFRAME_SECONDS,
  QUERY_COMPLEXITY_RATE_LIMIT_BY_IP_VALUE
};
